### ISSUE TITLE
index 0 is out of bounds for axis 0 with size 0

### ISSUE THREAD

**Issue by OsloAI** [neptune-ml/open-solution-salt-identification#92]
Could you tell me how to fix this problem? thanks

if: Expression Syntax.
then: Command not found.
2018-10-01 08-21-52 salt-detection >>> creating metadata
neptune: Executing in Offline Mode.

  0%|          | 0/2 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "/ddn/home/kaggle/salt_identification/main.py", line 770, in <module>
    prepare_metadata()
  File "/ddn/home/kaggle/salt_identification/main.py", line 351, in prepare_metadata
    depths_filepath=PARAMS.depths_filepath
  File "/ddn/home/kaggle/salt_identification/common_blocks/utils.py", line 134, in generate_metadata
    depth = depths[depths['id'] == image_id]['z'].values[0]
IndexError: index 0 is out of bounds for axis 0 with size 0

**Comment by jakubczakon** [comment]
Hi there @OsloAI and sorry for late response.

It seems that you are pointing to an empty directory of images in your `neptune.yaml`:

```yaml
parameters:
  # Data Paths
  train_images_dir: PATH/TO/YOUR/salt/data/train
  test_images_dir:  PATH/TO/YOUR/salt/data/test
```

Make sure that those two paths are correct.
